name: Dependency Updates

on:
  schedule:
    # Run every Monday at 6 AM UTC
    - cron: '0 6 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Update dependencies
      run: |
        # Update all dependencies to latest
        bun update
        
        # Check if there are changes
        if git diff --exit-code package.json bun.lock; then
          echo "No dependency updates available"
          exit 0
        fi
        
    - name: Run tests after update
      run: |
        bun install
        bun run tsc --noEmit
        bun run lint
        bun run build
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore(deps): update dependencies'
        title: '🔄 Automated Dependency Updates'
        body: |
          ## 🔄 Automated Dependency Updates
          
          This PR contains automated dependency updates.
          
          ### Changes
          - Updated all dependencies to their latest versions
          - All tests and builds are passing
          
          ### Verification
          - ✅ TypeScript compilation
          - ✅ ESLint checks  
          - ✅ Build successful
          
          Please review the changes and merge if everything looks good.
          
          ---
          *This PR was created automatically by GitHub Actions*
        branch: chore/dependency-updates
        delete-branch: true
        
  # Security audit
  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Install dependencies
      run: bun install --frozen-lockfile
      
    - name: Run security audit
      run: bun audit --audit-level moderate
      
    - name: Create issue on vulnerabilities
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: '🚨 Security Vulnerabilities Detected',
            body: `
            ## 🚨 Security Alert
            
            Security vulnerabilities have been detected in dependencies.
            
            Please run \`bun audit\` locally and update vulnerable packages.
            
            **Action Required:**
            1. Run \`bun audit\` to see detailed vulnerability report
            2. Update vulnerable dependencies
            3. Test the application
            4. Create a PR with the fixes
            
            ---
            *This issue was created automatically by GitHub Actions*
            `,
            labels: ['security', 'dependencies', 'critical']
          });
